---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: clang-format
        exclude: (CLI11\.hpp)
        args:
          - -style=file
          - -i
